[package]
name = "unit-tests"
version = "0.1.0"
edition = "2021"
rust-version = "1.65.0"
publish = false

[dev-dependencies]
bincode = "1.3.3"
blake3 = { workspace = true, features = ["traits-preview"] }
commit = { git = "https://github.com/EspressoSystems/commit" }
either = { version = "1.8" }
serde = { version = "1.0.194", features = ["derive"] }

hotshot-constants = { path = "../constants" }
hotshot-testing = { path = "../testing" }
hotshot-types = { path = "../types" }


[[test]]
name = "message"
path = "tests/message.rs"
