[package]
name = "hotstuff"
version = "0.0.0"
authors = ["Nathan McCarty <nathan.mccarty@translucence.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-lock = "2.4.0"
bincode = "1.3.2"
futures-channel = "0.3.13"
futures-lite = "1.11.3"
futures-locks = "0.6.0"
parking_lot = { version = "0.11.1", features = ["serde"] }
serde = { version = "1.0.123", features = ["derive", "rc"] }
snafu = { version = "0.6.10", features = ["backtraces"] }
threshold_crypto = "0.4.0"
