[package]
name = "phaselock-testing"
version = "0.0.1"
edition = "2021"
description = "Types and traits for the PhaseLock consesus module"
authors = ["Victor Koenders <vkoenders@espressosys.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
phaselock = { path = "../" }
phaselock-types = { path = "../phaselock-types" }
async-std = "1.3.0"
tracing = "0.1.32"
rand = "0.7.3"
