[package]
name = "networking-demo"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = { version = "1.10.0", features = ["attributes", "unstable"] }
bincode = "1.3.3"
blake3 = "1.3.0"
color-eyre = "0.6.0"
crossterm = { version = "0.22.1", features = ["event-stream"] }
flume = "0.10.10"
futures = "0.3.19"
libp2p = "0.41.1"
parking_lot = "0.11.2"
serde = { version = "1.0.133", features = ["derive"] }
snafu = "0.7.0"
structopt = "0.3.25"
tracing = "0.1.29"
tracing-error = "0.2.0"
tracing-subscriber = { version = "0.3.5", features = ["env-filter", "json"] }
tui = { version = "0.16.0", features = ["crossterm"], default-features = false }
rand = "0.8.4"
async-trait = "0.1.52"
