[package]
name = "networking-demo"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = { version = "1.10.0", features = ["attributes", "unstable"] }
bincode = "1.3.3"
blake3 = "1.3.1"
color-eyre = "0.6.1"
crossterm = { version = "0.23.0", features = ["event-stream"] }
flume = "0.10.11"
futures = "0.3.21"
libp2p = { version = "0.43.0", features = ["serde"] }
parking_lot = "0.12.0"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
snafu = "0.7.0"
structopt = "0.3.26"
tracing = "0.1.31"
tracing-error = "0.2.0"
tracing-subscriber = { version = "0.3.9", features = ["env-filter", "json"] }
tui = { version = "0.17.0", features = ["crossterm"], default-features = false }
rand = "0.8.5"
async-trait = "0.1.52"
derive_builder = "0.10.2"
