[package]
name = "networking-demo"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = { version = "1.10.0", features = ["attributes"] }
bincode = "1.3.3"
color-eyre = "0.5.11"
crossterm = "0.22.1"
libp2p = "0.41.1"
parking_lot = "0.11.2"
serde = { version = "1.0.133", features = ["derive"] }
snafu = "0.7.0"
tracing = "0.1.29"
tui = { version = "0.16.0", features = ["crossterm"], default-features = false }
