[package]
authors = ["Espresso Systems <hello@espressosys.com>"]
description = "Accompanying utilities used by hotshot."
edition = "2021"
name = "hotshot-utils"
readme = "../README.md"
version = "0.1.0"

[dependencies]
bincode = "1.3.3"