name: Build Workflow for ARM

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
      - '*/*'
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, arm64]
    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
        name: Cancel Outdated Builds
        with:
          all_but_latest: true
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3
        name: Checkout Repository

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - uses: Swatinem/rust-cache@v2
        name: Enable Rust Caching

      - name: Build all crates in workspace
        run: cargo build --verbose --profile=release-lto --features=full-ci --all-targets
